### ISSUE TITLE
NegBin and ZINB RNG wrappers should allow vectors for `alpha`

### ISSUE THREAD

**Issue by gavinsimpson** [gavinsimpson/coenocliner#25]
As mentioned by @jarioksa in #24, `NegBin` and `ZINB` should ideally take vector inputs for argument `alpha`. The fix in #24 assumes a "scalar" input. Currently this isn't much of a problem as, from #16, we don't allow vector `countParams`, but this will change in time for the 0.3 release of coenocliner.

This issue is to track this problem and make sure it is fixed with #16 if not before.

**Comment by jarioksa** [comment]
I have two alternative fixes for these in my clone:

https://github.com/jarioksa/coenocliner/tree/rgamma-zero-quick-fix
https://github.com/jarioksa/coenocliner/tree/rgamma-zero-vector-fix

Feel free to do anything you want with these.

**Comment by gavinsimpson** [comment]
Thanks @jarioksa. I used a slightly different approach but effectively the same as what you achieve via the `ifelse()` fix. (I just find which elements of `alpha` are `> 0L` and then replace those with new `mu * rgamm()` values, levaing the `alpha == 0` values alone.)

I am going to leave negative `alpha` as a error; silently changing underdispersed Poisson to a standard Poisson is probably going to bite someone at some point.

**Comment by gavinsimpson** [comment]
Implemented via 5817b17
